/* 계정 생성 (in 관리자 계정)*/
-- USER SQL
CREATE USER camtudy IDENTIFIED BY 1004 DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
    
-- ROLES
GRANT "CONNECT" TO camtudy ;
GRANT "RESOURCE" TO camtudy ;
ALTER USER camtudy DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES


/* DB Table 및 Sequence 생성(in camtudy 계정) */
/* ADMIN */
CREATE TABLE ADMIN (
	ID_ADMIN VARCHAR2(200) NOT NULL, /* ID_ADMIN */
	PWD_ADMIN VARCHAR2(200) NOT NULL /* PWD_ADMIN */
);

/* CATEGORY */
CREATE TABLE CATEGORY (
	NO_CATEGORY NUMBER NOT NULL, /* NO_CATEGORY */
	NAME_CATEGORY VARCHAR2(50) NOT NULL /* NAME_CATEGORY */
);

CREATE UNIQUE INDEX PK_CATEGORY
	ON CATEGORY (
		NO_CATEGORY ASC
	);

ALTER TABLE CATEGORY
	ADD
		CONSTRAINT PK_CATEGORY
		PRIMARY KEY (
			NO_CATEGORY
		);

/* EXAM */
CREATE TABLE EXAM (
	NUM_EXAM NUMBER NOT NULL, /* NUM_EXAM */
	TITLE_EXAM VARCHAR2(200) NOT NULL, /* TITLE_EXAM */
	ID_MEM VARCHAR2(200) NOT NULL, /* ID_MEM */
	CATEGORY_EXAM VARCHAR2(200) NOT NULL, /* CATEGORY_EXAM */
	VIEW_COUNT_EXAM NUMBER NOT NULL, /* VIEW_COUNT_EXAM */
	COUNT_EXAM NUMBER NOT NULL, /* COUNT_EXAM */
	RECOMAND_COUNT_EXAM NUMBER NOT NULL, /* RECOMAND_COUNT_EXAM */
	DATE_EXAM DATE NOT NULL /* DATE_EXAM */
);

CREATE UNIQUE INDEX PK_EXAM
	ON EXAM (
		NUM_EXAM ASC
	);

ALTER TABLE EXAM
	ADD
		CONSTRAINT PK_EXAM
		PRIMARY KEY (
			NUM_EXAM
		);

/* FREE */
CREATE TABLE FREE (
	NO_FREE NUMBER NOT NULL, /* NO_FREE */
	TITLE_FREE VARCHAR2(100) NOT NULL, /* TITLE_FREE */
	WRITER_FREE VARCHAR2(20) NOT NULL, /* WRITER_FREE */
	CONTENT_FREE VARCHAR2(2000) NOT NULL, /* CONTENT_FREE */
	HIT_FREE NUMBER NOT NULL, /* HIT_FREE */
	REGDATE_FREE DATE, /* REGDATE_FREE */
	DELETED_FREE NUMBER NOT NULL, /* DELETED_FREE */
	GROUPNO_FREE NUMBER NOT NULL, /* GROUPNO_FREE */
	STEP_FREE NUMBER NOT NULL, /* STEP_FREE */
	DEPTH_FREE NUMBER NOT NULL /* DEPTH_FREE */
);

CREATE UNIQUE INDEX PK_FREE
	ON FREE (
		NO_FREE ASC
	);

ALTER TABLE FREE
	ADD
		CONSTRAINT PK_FREE
		PRIMARY KEY (
			NO_FREE
		);

/* LIST */
CREATE TABLE LIST (
	NO_STUDY NUMBER NOT NULL, /* NO_STUDY */
	NO_MEM NUMBER NOT NULL, /* NO_MEM */
	POINT_LIST NUMBER NOT NULL, /* POINT_LIST */
	ACC_TIME_LIST NUMBER NOT NULL, /* ACC_TIME_LIST */
	LATNESS NUMBER NOT NULL, /* LATNESS */
	ABSENCE NUMBER NOT NULL /* ABSENCE */
);

CREATE UNIQUE INDEX PK_LIST
	ON LIST (
		NO_STUDY ASC,
		NO_MEM ASC
	);

ALTER TABLE LIST
	ADD
		CONSTRAINT PK_LIST
		PRIMARY KEY (
			NO_STUDY,
			NO_MEM
		);

/* MEMBER */
CREATE TABLE MEMBER (
	NO_MEM NUMBER NOT NULL, /* NO_MEM */
	ID_MEM VARCHAR2(200) NOT NULL, /* ID_MEM */
	PWD_MEM VARCHAR2(200) NOT NULL, /* PWD_MEM */
	NAME_MEM VARCHAR2(20) NOT NULL, /* NAME_MEM */
	EMAIL_MEM VARCHAR2(200) NOT NULL, /* EMAIL_MEM */
	INTRO_MEM VARCHAR2(200) NOT NULL /* INTRO_MEM */
);

CREATE UNIQUE INDEX PK_MEMBER
	ON MEMBER (
		NO_MEM ASC
	);

ALTER TABLE MEMBER
	ADD
		CONSTRAINT PK_MEMBER
		PRIMARY KEY (
			NO_MEM
		);

/* QNA */
CREATE TABLE QNA (
	NO_QNA NUMBER NOT NULL, /* NO_QNA */
	TITLE_QNA VARCHAR2(100) NOT NULL, /* TITLE_QNA */
	WRITER_QNA VARCHAR2(20) NOT NULL, /* WRITER_QNA */
	CONTENT_QNA VARCHAR2(2000) NOT NULL, /* CONTENT_QNA */
	HIT_QNA NUMBER NOT NULL, /* HIT_QNA */
	REGDATE_QNA DATE, /* REGDATE_QNA */
	DELETED_QNA NUMBER NOT NULL, /* DELETED_QNA */
	GROUPNO_QNA NUMBER NOT NULL, /* GROUPNO_QNA */
	STEP_QNA NUMBER NOT NULL, /* STEP_QNA */
	DEPTH_QNA NUMBER NOT NULL /* DEPTH_QNA */
);

CREATE UNIQUE INDEX PK_QNA
	ON QNA (
		NO_QNA ASC
	);

ALTER TABLE QNA
	ADD
		CONSTRAINT PK_QNA
		PRIMARY KEY (
			NO_QNA
		);

/* QUESTION */
CREATE TABLE QUESTION (
	NUM_EXAM NUMBER NOT NULL, /* NUM_EXAM */
	NUM_QUESTION NUMBER NOT NULL, /* NUM_QUESTION */
	TYPE_QUESTION VARCHAR2(20) NOT NULL, /* TYPE_QUESTION */
	CONTENT_QUESTION VARCHAR2(4000) NOT NULL, /* CONTENT_QUESTION */
	ANSWER_LIST_QUESTION VARCHAR2(4000) NOT NULL, /* ANSWER_LIST_QUESTION */
	ANSWER_QUESTION VARCHAR2(4000) NOT NULL /* ANSWER_QUESTION */
);

CREATE UNIQUE INDEX PK_QUESTION
	ON QUESTION (
		NUM_EXAM ASC,
		NUM_QUESTION ASC
	);

ALTER TABLE QUESTION
	ADD
		CONSTRAINT PK_QUESTION
		PRIMARY KEY (
			NUM_EXAM,
			NUM_QUESTION
		);

/* RECRUIT */
CREATE TABLE RECRUIT (
	NUM_RECRUIT NUMBER NOT NULL, /* NUM_RECRUIT */
	NAME_RECRUIT VARCHAR2(50), /* NAME_RECRUIT */
	PWD_RECRUIT VARCHAR2(20), /* PWD_RECRUIT */
	SUBJECT_RECRUIT VARCHAR2(50), /* SUBJECT_RECRUIT */
	CONTENT_RECRUIT VARCHAR2(2000), /* CONTENT_RECRUIT */
	REGDATE_RECRUIT DATE, /* REGDATE_RECRUIT */
	HIT_RECRUIT NUMBER, /* HIT_RECRUIT */
	PARENT_RECRUIT NUMBER, /* PARENT_RECRUIT */
	SORT_RECRUIT NUMBER, /* SORT_RECRUIT */
	TAB_RECRUIT NUMBER /* TAB_RECRUIT */
);

CREATE UNIQUE INDEX PK_RECRUIT
	ON RECRUIT (
		NUM_RECRUIT ASC
	);

ALTER TABLE RECRUIT
	ADD
		CONSTRAINT PK_RECRUIT
		PRIMARY KEY (
			NUM_RECRUIT
		);

/* RESULT */
CREATE TABLE RESULT (
	NUM_EXAM NUMBER NOT NULL, /* NUM_EXAM */
	NO_MEM NUMBER NOT NULL, /* NO_MEM */
	SCORE_EXAM NUMBER NOT NULL, /* SCORE_EXAM */
	DATE_EXAM DATE NOT NULL /* DATE_EXAM */
);

CREATE UNIQUE INDEX PK_RESULT
	ON RESULT (
		NUM_EXAM ASC,
		NO_MEM ASC
	);

ALTER TABLE RESULT
	ADD
		CONSTRAINT PK_RESULT
		PRIMARY KEY (
			NUM_EXAM,
			NO_MEM
		);

/* STUDY */
CREATE TABLE STUDY (
	NO_STUDY NUMBER NOT NULL, /* NO_STUDY */
	NAME_STUDY VARCHAR2(50) NOT NULL, /* NAME_STUDY */
	MANAGER_NO_STUDY NUMBER NOT NULL, /* MANAGER_NO_STUDY */
	MANAGER_ID_STUDY VARCHAR2(200) NOT NULL, /* MANAGER_ID_STUDY */
	CATEGORY_STUDY VARCHAR2(50) NOT NULL, /* CATEGORY_STUDY */
	NUMBEROFMEM_STUDY NUMBER NOT NULL, /* NUMBEROFMEM_STUDY */
	MAXMEMBER_STUDY NUMBER NOT NULL, /* MAXMEMBER_STUDY */
	DATE_START_STUDY VARCHAR2(50) NOT NULL, /* DATE_START_STUDY */
	DATE_END_STUDY VARCHAR2(50) NOT NULL, /* DATE_END_STUDY */
	TIME_START_STUDY NUMBER NOT NULL, /* TIME_START_STUDY */
	TIME_END_STUDY NUMBER NOT NULL, /* TIME_END_STUDY */
	LATENESS_PANALTY_STUDY NUMBER NOT NULL, /* LATENESS_PANALTY_STUDY */
	LATNESS_TIME_STUDY NUMBER NOT NULL, /* LATNESS_TIME_STUDY */
	ABSENCE_PANALTY_STUDY NUMBER NOT NULL, /* ABSENCE_PANALTY_STUDY */
	NOTICE_STUDY VARCHAR2(300) /* NOTICE_STUDY */
);

CREATE UNIQUE INDEX PK_STUDY
	ON STUDY (
		NO_STUDY ASC
	);

ALTER TABLE STUDY
	ADD
		CONSTRAINT PK_STUDY
		PRIMARY KEY (
			NO_STUDY
		);

ALTER TABLE LIST
	ADD
		CONSTRAINT FK_STUDY_TO_LIST
		FOREIGN KEY (
			NO_STUDY
		)
		REFERENCES STUDY (
			NO_STUDY
		);

ALTER TABLE LIST
	ADD
		CONSTRAINT FK_MEMBER_TO_LIST
		FOREIGN KEY (
			NO_MEM
		)
		REFERENCES MEMBER (
			NO_MEM
		);

ALTER TABLE QUESTION
	ADD
		CONSTRAINT FK_EXAM_TO_QUESTION
		FOREIGN KEY (
			NUM_EXAM
		)
		REFERENCES EXAM (
			NUM_EXAM
		);

ALTER TABLE RESULT
	ADD
		CONSTRAINT FK_EXAM_TO_RESULT
		FOREIGN KEY (
			NUM_EXAM
		)
		REFERENCES EXAM (
			NUM_EXAM
		);

ALTER TABLE RESULT
	ADD
		CONSTRAINT FK_MEMBER_TO_RESULT
		FOREIGN KEY (
			NO_MEM
		)
		REFERENCES MEMBER (
			NO_MEM
		);
		
/*Sequence 생성*/
CREATE SEQUENCE  seq_no_study  START WITH 1  INCREMENT BY 1;
CREATE SEQUENCE  seq_no_mem  START WITH 1  INCREMENT BY 1;
CREATE SEQUENCE  seq_num_exam  START WITH 1  INCREMENT BY 1;
CREATE SEQUENCE  seq_no_category  START WITH 1  INCREMENT BY 1;
CREATE SEQUENCE  seq_NO_FREE  START WITH 1  INCREMENT BY 1;
CREATE SEQUENCE  seq_NO_RECRUIT  START WITH 1  INCREMENT BY 1;
CREATE SEQUENCE  seq_NO_QNA  START WITH 1  INCREMENT BY 1;		

/*Amdin 계정 생성: ID -> admin , pwd -> 1004 */
insert into admin values ('admin','1004');   

/*Category data 생성*/
insert into category values (1,'고시');
insert into category values (2,'공무원');
insert into category values (3,'취업');
insert into category values (4,'자격증');
insert into category values (5,'어학');
insert into category values (6,'대입');
insert into category values (7,'기타');

/* Test member 생성*/
insert into member values(0,'camtudy','1004','고시생','test@naver.com','열공합시다');

/*필수*/
commit;